core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

     {% block extra_body %}
     {% endblock %}

    {% include "footer.html"%}
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}
<style type="text/css">
	.selection-2{
	display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
</style>

	<!-- Title Page -->
		<h2 class="l-text2 t-center">
			<h1 style="text-align:center"><strong><span style="font-size:36px"><span style="font-family:Comic Sans MS,cursive">{{ category_title }}</span></span></strong></h1>
			<p style="text-align:center"><strong><span style="font-size:16px"><span style="font-family:Courier New,Courier,monospace"><em>{{ category_description }}</em></span></span></strong></p>

		</p>
	</section>


	<!-- Content page -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						<!--  -->
						<h4 class="m-text14 p-b-7">
							Categories
						</h4>

						<ul class="p-b-54">
							<li class="p-t-4">
								<a href="/shop" class="s-text13 active1">
									Все
								</a>
							</li>

							{% categories_li_a %}

						</ul>

						<!--  -->
						<h4 class="m-text14 p-b-32">
						</h4>

						<div class="">
							<div class="">
							</div>

							<div class="">
								<div id=""></div>
							</div>

							<div class="">
								<div class="">
									<!-- Button -->
								</div>

							</div>
						</div>

						<div class="">
							<div class="">
							</div>

							</ul>
						</div>


					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->
					<div class="flex-sb-m flex-w p-b-35">
						<div class="flex-w">

						</div>

						<span class="s-text8 p-t-5 p-b-5">
							Showing 1–12 of 16 results
						</span>
					</div>

					<!-- Product -->
					<div class="row">
						{% for item in object_list %}
						<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
							<!-- Block2 -->
							<div class="block2">
								<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
									<img src="{{ item.image.url }}" alt="IMG-PRODUCT"
								style="height: 360px;">

									<div class="block2-overlay trans-0-4">
										<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
											<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
											<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
										</a>

										<a href="{{item.get_absolute_url }}" class="btn btn-primary" style="margin: 20em auto;">Подробнее</a>

									</div>
								</div>

								<div class="block2-txt p-t-20">
									<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5">
										{{item.title}}
									</a>

									<span class="block2-price m-text6 p-r-5">
										${{item.price}}
									</span>
								</div>
							</div>
						</div>
						{% endfor %}

						

						
				
				</div>
				<!-- ---- row end ------- -->

				<br>
				<!-- Pagination -->
				{% if is_paginated %}
				<div class="pagination flex-m flex-w p-t-26">
					{% if page_obj.has_previous %}
					<a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
					{% endif %}
					<a href="?page={{ page_obj.number }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{page_obj.number}}</a>
					
					
					{% if page_obj.has_next %}
					<a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
	</section>


		{% endblock content %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}

<h1> Для заказа обращайтесь в вайбер: +380680874711 </h1>
{% endblock content%}

templates/header.html
{% load static %}
<head>
  <title>Home</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--===============================================================================================-->
  <link
    rel="icon"
    type="image/png"
    href="{% static 'images/icons/favicon.png' %}"
  />
  <!--===============================================================================================-->

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  />

  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/themify/themify-icons.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/elegant-font/html-css/style.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animate/animate.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animsition/css/animsition.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/select2/select2.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/daterangepicker/daterangepicker.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/slick/slick.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}"
  />
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css">
  <!--===============================================================================================-->
</head>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% load slide_template_tags %}
{% block content %}
<style>
	/*[ Block2 ]
///////////////////////////////////////////////////////////
*/
.block2-labelpromotion::before,
.block2-labelsale::before,
.block2-labelnew::before 
{
  z-index: 100;
  font-family: Montserrat-Regular;
  font-size: 12px;
  color: white;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 22px;
  border-radius: 11px;
  position: absolute;
  top: 12px;
  left: 12px;
}

.block2-labelsale::before {
  background-color: white;
  color: #000;
  content: 'Sale';
}

.block2-labelnew::before {
  background-color: #007bff;
  content: 'New';
}

.block2-labelpromotion::before{
	background-color: #000;
	content: 'Promotion';
	width: 70px;
  }

  .btn-dark {
    color: #fff;
    background-color: #000;
    border-color: #000;
}

.btn-outline-dark {
    color: #000;
    border-color: #000;
}


</style>

	<!-- Slide1 -->

			</div>
	</section>

	<!-- Category start -->
			</div>
		</div>
	</section>

	</section>

<h1 style="text-align:center"><strong><span style="font-size:36px"><span style="font-family:Comic Sans MS,cursive">О НАС</span></span></strong></h1>

<p style="text-align:center"><strong><span style="font-size:16px"><span style="font-family:Courier New,Courier,monospace"><em>Аренда костюмов</em></span></span></strong></p>

{% endblock content %}

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->


				<span class="topbar-child1">
				</span>

				<div class="topbar-child2">
					<span class="topbar-email">
					    </a>
					</span>

					<div class="topbar-language rs1-select2">

					</div>
				</div>
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">V</b>ILLA ROSE</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">

							<li>
								<a href="/shop/">Магазин</a>
							</li>

							<li>
								<a href="/">О нас</a>
							</li>

							{% categories %}

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:order-summary' %}">Корзина<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">Выйти</a>
							</li>
							{% else %}
							<li>
								<a href="#">Логин</a>
								<ul class="sub_menu">
									<li><a href="{% url 'account_login' %}">Логин</a></li>
									<li><a href="{% url 'account_signup' %}">Регистрация</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->









		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="index.html" class="logo-mobile">
				<img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>




									</

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>



					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>

      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 style="text-align:center"><strong><span style="font-size:36px"><span style="font-family:Comic Sans MS,cursive">Заказ</span></span></strong></h1>
      <br>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Фото</th>
            <th scope="col">Имя</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Окончательная цена</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ₴{{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ₴{{ order_item.get_amount_saved }}</span>
              {% else %}
              ₴{{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ₴{{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
          <td colspan="5"><b> <h3> Общая сумма заказа: </h3> </b></td>
        	<td><b><h2> ₴{{ object.get_total }}</h2></b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Заказать</a>
        		<a href="/shop" class="btn btn-primary float-right">Продолжить покупки </a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}

templates/payment.html
 <h1> Спасибо за заказ, мы свяжемся с вами по телефону!</h1>

templates/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'core:category' object.category.slug %}" class="s-text16">
			{{ object.category }}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{object.title}}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">
						<div class="item-slick3" data-thumb="{{ object.image.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image.url }}" alt="{{ object.title }}">
							</div>
						</div>



						</div>
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{object.title}}
				</h4>

				
				{% if object.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="font-size: 1.5rem;">
									₴ {{ object.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5" style="font-size: 1.5rem;">
									₴ {{ object.discount_price }}
								</span>
								{% else %}
								<span class="m-text17">
									₴ {{object.price}}
								</span>
								{% endif %}
				<div class="p-b-45">
					<span class="s-text8">Категория: {{ object.category }}</span>
					<br>
				</div>

				<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Description
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							{{ object.description_long }}
						</p>
					</div>
				</div>


				<p class="s-text8 p-t-10">
					{{ object.description_short }}
				</p>

				<!--  -->
				<div class="p-t-33 p-b-60">
					<div class="flex-m flex-w p-b-10">
						<div class="s-text15 w-size15 t-center">
						</div>


						</div>
					</div>


				<a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary" style="margin: 2px;">Add to Cart</a>
				<a href="{{object.get_remove_from_cart_url}}" class="btn btn-outline-dark" style="margin: 2px;">Remove from Cart</a>

					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">

							
							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10" style="margin-bottom: 20px;">



							</div>
							
 						</div>
					</div>
				</div>
				<br>


				<!--  -->

			</div>
					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	</section>
	{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>Request Refund</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}